### ISSUE TITLE
java.lang.NoSuchMethodError: javax/servlet/ServletContext.getClassLoader() is thrown when deploying in tomcat 6

### ISSUE THREAD

**Issue by jorgediaz-lr** [jorgediaz-lr/index-checker#1]
Error `java.lang.NoSuchMethodError: javax/servlet/ServletContext.getClassLoader()Ljava/lang/ClassLoader;` is thrown when deploying in tomcat 6

````
22:57:12,344 ERROR [ContainerBackgroundProcessor[StandardEngine]][HotDeployImpl:233] com.liferay.portal.kernel.deploy.hot.HotDeployException: Error registering portlets for index_checker-portletindex_checker-portlet
com.liferay.portal.kernel.deploy.hot.HotDeployException: Error registering portlets for index_checker-portletindex_checker-portlet
at com.liferay.portal.kernel.deploy.hot.BaseHotDeployListener.throwHotDeployException(BaseHotDeployListener.java:46)
at com.liferay.portal.deploy.hot.PortletHotDeployListener.invokeDeploy(PortletHotDeployListener.java:128)
[...]
at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1653)
at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1662)
at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1642)
at java.lang.Thread.run(Thread.java:798)
Caused by: java.lang.NoSuchMethodError: javax/servlet/ServletContext.getClassLoader()Ljava/lang/ClassLoader;
at jorgediazest.util.model.ModelUtil.getClassLoader(ModelUtil.java:120)
at jorgediazest.util.model.ModelFactory.getModelMap(ModelFactory.java:58)
at jorgediazest.indexchecker.model.IndexCheckerModelFactory.getModelMap(IndexCheckerModelFactory.java:85)
at jorgediazest.indexchecker.portlet.IndexCheckerPortlet.init(IndexCheckerPortlet.java:602)
[...]
at com.liferay.portal.deploy.hot.PortletHotDeployListener.doInvokeDeploy(PortletHotDeployListener.java:370)
at com.liferay.portal.deploy.hot.PortletHotDeployListener.invokeDeploy(PortletHotDeployListener.java:125)
... 27 more

**Comment by jorgediaz-lr** [comment]
Solved in version **0.3 - beta**:
   - https://github.com/jorgediaz-lr/index-checker/releases/tag/0.3_beta3_6.2
