### ISSUE TITLE
Prepared or callable statement has more than 2000 parameter markers

### ISSUE THREAD

**Issue by denissignoretto** [jorgediaz-lr/index-checker#7]
I'm facing this issue in a Liferay 6.2.5 with 0.6 IndexChecker plugin installed. The portal has more than 4500 users 

[13.09.2017 15:05:52,267 +0200] INFO  [pool-11718-thread-1][jorgediazest.indexchecker.portlet.CallableCheckGroupAndModel:215] Model: com.liferay.portal.model.Contact - CompanyId: 20155 - GroupId: [0, 20195, 20182]
[13.09.2017 15:05:52,279 +0200] ERROR [pool-11718-thread-1][org.hibernate.util.JDBCExceptionReporter:82] Prepared or callable statement has more than 2000 parameter markers. 
[13.09.2017 15:05:52,279 +0200] ERROR [pool-11718-thread-1][com.liferay.portal.service.persistence.impl.BasePersistenceImpl:244] Caught unexpected exception org.hibernate.exception.DataException
[13.09.2017 15:05:52,280 +0200] ERROR [pool-11718-thread-1][jorgediazest.util.data.ComparisonUtil:109] Model: com.liferay.portal.model.Contact EXCEPTION: class java.lang.RuntimeException - executeMethod: dynamicQuery method for com.liferay.portal.service.impl.ContactLocalServiceImpl@63f031cd: (root cause: org.hibernate.exception.DataException: could not execute query) java.lang.RuntimeException: executeMethod: dynamicQuery method for com.liferay.portal.service.impl.ContactLocalServiceImpl@63f031cd: (root cause: org.hibernate.exception.DataException: could not execute query) at jorgediazest.util.service.ServicePersistedModelImpl.executeServiceMethod(ServicePersistedModelImpl.java:125) at jorgediazest.util.service.ServicePersistedModelImpl.executeDynamicQuery(ServicePersistedModelImpl.java:92) at jorgediazest.util.modelquery.ModelQueryImpl.getDataWithDuplicates(ModelQueryImpl.java:406) at jorgediazest.util.modelquery.ModelQueryImpl.getData(ModelQueryImpl.java:274) at jorgediazest.util.modelquery.ModelQueryImpl.getData(ModelQueryImpl.java:300) at jorgediazest.util.modelquery.ModelQueryImpl.getData(ModelQueryImpl.java:292) at jorgediazest.indexchecker.model.IndexCheckerModelQuery.getData(IndexCheckerModelQuery.java:204) at jorgediazest.indexchecker.portlet.CallableCheckGroupAndModel.call(CallableCheckGroupAndModel.java:241) at jorgediazest.indexchecker.portlet.CallableCheckGroupAndModel.call(CallableCheckGroupAndModel.java:1) at java.util.concurrent.FutureTask.run(FutureTask.java:262) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at java.lang.Thread.run(Thread.java:745) Caused by: java.lang.reflect.InvocationTargetException at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:606) at jorgediazest.util.service.ServicePersistedModelImpl.executeServiceMethod(ServicePersistedModelImpl.java:110) ... 12 more Caused by: com.liferay.portal.kernel.exception.SystemException: org.hibernate.exception.DataException: could not execute query at com.liferay.portal.service.persistence.impl.BasePersistenceImpl.processException(BasePersistenceImpl.java:251) at com.liferay.portal.service.persistence.impl.BasePersistenceImpl.findWithDynamicQuery(BasePersistenceImpl.java:144) at com.liferay.portal.service.base.ContactLocalServiceBaseImpl.dynamicQuery(ContactLocalServiceBaseImpl.java:213) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:606) at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:115) at com.liferay.portal.spring.transaction.DefaultTransactionExecutor.execute(DefaultTransactionExecutor.java:62) at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:51) at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:111) at com.liferay.portal.spring.aop.ServiceBeanAopProxy.invoke(ServiceBeanAopProxy.java:175) at com.sun.proxy.$Proxy32.dynamicQuery(Unknown Source) ... 17 more Caused by: org.hibernate.exception.DataException: could not execute query at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:102) at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:66) at org.hibernate.loader.Loader.doList(Loader.java:2545) at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2276) at org.hibernate.loader.Loader.list(Loader.java:2271) at org.hibernate.loader.criteria.CriteriaLoader.list(CriteriaLoader.java:119) at org.hibernate.impl.SessionImpl.list(SessionImpl.java:1716) at org.hibernate.impl.CriteriaImpl.list(CriteriaImpl.java:347) at com.liferay.portal.dao.orm.hibernate.DynamicQueryImpl.list(DynamicQueryImpl.java:94) at com.liferay.portal.dao.orm.hibernate.DynamicQueryImpl.list(DynamicQueryImpl.java:88) at com.liferay.portal.service.persistence.impl.BasePersistenceImpl.findWithDynamicQuery(BasePersistenceImpl.java:141) ... 28 more Caused by: java.sql.SQLException: Prepared or callable statement has more than 2000 parameter markers. at net.sourceforge.jtds.jdbc.SQLParser.parse(SQLParser.java:1139) at net.sourceforge.jtds.jdbc.SQLParser.parse(SQLParser.java:156) at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.<init>(JtdsPreparedStatement.java:98) at net.sourceforge.jtds.jdbc.ConnectionJDBC2.prepareStatement(ConnectionJDBC2.java:2445) at net.sourceforge.jtds.jdbc.ConnectionJDBC2.prepareStatement(ConnectionJDBC2.java:2403) at com.mchange.v2.c3p0.impl.NewProxyConnection.prepareStatement(NewProxyConnection.java:469) at sun.reflect.GeneratedMethodAccessor96.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:606) at org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy$LazyConnectionInvocationHandler.invoke(LazyConnectionDataSourceProxy.java:376) at com.sun.proxy.$Proxy4.prepareStatement(Unknown Source) at org.hibernate.jdbc.AbstractBatcher.getPreparedStatement(AbstractBatcher.java:534) at org.hibernate.jdbc.AbstractBatcher.getPreparedStatement(AbstractBatcher.java:452) at org.hibernate.jdbc.AbstractBatcher.prepareQueryStatement(AbstractBatcher.java:161) at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1700) at org.hibernate.loader.Loader.doQuery(Loader.java:801) at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:274) at org.hibernate.loader.Loader.doList(Loader.java:2542) ... 36 more

**Comment by jorgediaz-lr** [comment]
Hi @denissignoretto 

Can you add the log file in the issue as an attachment? It is difficult to read exception in message.
Also tell me which options did you selected in portlet interface.

Thank you for reporting!

**Comment by jorgediaz-lr** [comment]
This issue was resolved in following commit https://github.com/jorgediaz-lr/index-checker/commit/a8464070e1d8dd7f35ceb4617916a6fe13050c73#diff-336e1cf131c3fbd6282948756601f822R68

It will be included in next Index Checker release

**Comment by jorgediaz-lr** [comment]
Solved in version 0.7:

https://github.com/jorgediaz-lr/index-checker/releases/tag/0.7_release_6.2

**Comment by denissignoretto** [comment]
Hi Jorge, sorry I've just seen your reply. I'll test version 0.7 on my installation with more than 2000 users as soon I can and I'll give you a feedback.

**Comment by jorgediaz-lr** [comment]
Hi @denissignoretto 

Thank you for reporting the bug, I will wait to your feedback with the new version.

Jorge

**Comment by denissignoretto** [comment]
Hi @jorgediaz-lr ,

I've updated 0.7 on a system with more than 6k users and now I can confirm you the issue has been solved.

Denis.

**Comment by jorgediaz-lr** [comment]
Hi @denissignoretto 

Thank you for the confirmation.

Jorge
